version: '3'
services:
  app:
    ports:
      - 3000:3000
    build:
      context: ./
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
